apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    component: app
  ports:
  - port: {{ .Values.app.ports.internal }}
    targetPort: {{ .Values.app.ports.internal }}

---

{{ if .Values.useSealedSecrets -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    {{- with .Values.sealedSecretsScope }}
    sealedsecrets.bitnami.com/{{ . }}: "true"
    {{- end }}
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    type: Opaque
  encryptedData:
    DIVESITE_DB_DSN: {{ .Values.app.database.dsn }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.namespace }}
data:
  DIVESITE_DB_DSN: {{ .Values.app.database.dsn }}
type: Opaque
{{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: app
        technology: golang
    spec:
      initContainers:
      - name: db-migrate
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
        command: "/migrate"
        args:
        - --path
        - "/migrations/"
        - --db-dsn
        - "$(DIVESITE_DB_DSN)"
        - up
        {{- with .Values.app.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ .Chart.Name }}-secrets
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
        args:
        - --addr
        - ":{{ .Values.app.ports.internal }}"
        - --db-dsn
        - "$(DIVESITE_DB_DSN)"
        ports:
        - containerPort: {{ .Values.app.ports.internal }}
        {{- if .Values.app.probes.liveness.active }}
        livenessProbe:
          httpGet:
            path: {{ .Values.app.probes.liveness.path }}
            port: {{ .Values.app.ports.internal }}
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
        {{- end }}
        {{- with .Values.app.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ .Chart.Name }}-secrets
      serviceAccountName: {{ .Chart.Name }}
      terminationGracePeriodSeconds: {{ .Values.app.terminationGracePeriodSeconds }}

