apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    component: app
  ports:
  - port: {{ .Values.app.ports.internal }}
    targetPort: {{ .Values.app.ports.internal }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  DIVESITE_DB_PORT: {{ quote .Values.app.database.port}}

---

{{ if .Values.useSealedSecrets -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    type: Opaque
  encryptedData:
    DIVESITE_DB_HOST: {{ .Values.app.database.host }}
    DIVESITE_DB_NAME: {{ .Values.app.database.name }}
    DIVESITE_DB_PASSWORD: {{ .Values.app.database.password }}
    DIVESITE_DB_USERNAME: {{ .Values.app.database.username }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.namespace }}
data:
  DIVESITE_DB_HOST: {{ b64enc .Values.app.database.host }}
  DIVESITE_DB_NAME: {{ b64enc .Values.app.database.name }}
  DIVESITE_DB_PASSWORD: {{ b64enc .Values.app.database.password }}
  DIVESITE_DB_USERNAME: {{ b64enc .Values.app.database.username }}
type: Opaque
{{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: app
        technology: golang
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.app.ports.internal }}
        {{- if .Values.app.probes.liveness.active }}
        livenessProbe:
          httpGet:
            path: {{ .Values.app.probes.liveness.path }}
            port: {{ .Values.app.ports.internal }}
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
        {{- end }}
        {{- with .Values.app.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config
        - secretRef:
            name: {{ .Chart.Name }}-secrets
      serviceAccountName: {{ .Chart.Name }}
      terminationGracePeriodSeconds: {{ .Values.app.terminationGracePeriodSeconds }}

