{{ if and .Values.dbBackup.active (eq .Values.app.database.engine "postgresql") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-database-backups
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dbBackup.volume.capacity }}
  storageClassName: {{ .Values.dbBackup.volume.storageClass }}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup-data
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.dbBackup.schedule}}
  jobTemplate:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: database
        technology: postgres
        job: database-backup-data
    spec:
      template:
        spec:
          containers:
          - name: database-backup-data
            image: docker.io/postgres:17-alpine
            command:
            - /bin/sh
            args:
            - -c
            - |
              ls -l /var/lib/postgresql/backups/ && \
              pg_dump ${DIVESITE_DB_DSN} \
                      > /var/lib/postgresql/backups/$(date +"%Y%m%d%H%M%S").sql && \
              echo "Removing backups older than ${BACKUP_RETENTION_DAYS} days" && \
              find /var/lib/postgresql/backups/ \
                   -type f \
                   -name "*.sql" \
                   -mtime +${BACKUP_RETENTION_DAYS} \
                   -delete && \
              ls -l /var/lib/postgresql/backups/
            env:
            - name: BACKUP_RETENTION_DAYS
              value: {{ quote .Values.dbBackup.retentionDays }}
            - name: DIVESITE_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: DIVESITE_DB_DSN
            {{- with .Values.app.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:
            - name: database-backups
              mountPath: /var/lib/postgresql/backups/
          restartPolicy: OnFailure
          serviceAccountName: {{ .Chart.Name }}
          volumes:
          - name: database-backups
            persistentVolumeClaim:
              claimName: {{ .Chart.Name }}-database-backups
{{- end }}

